import = ["$XDG_CONFIG_HOME/alacritty/an-old-hope.toml"]

live_config_reload = false

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "xterm-256color"

 [colors]
 draw_bold_text_with_bright_colors = true

 [colors.normal]
 black="0x0c0c0c"
 red="0xc50f1f"
 green="0x13a10e"
 yellow="0xc19c00"
 blue="0x0037da"
 magenta="0x881798"
 cyan="0x3a96dd"
 white="0xcccccc"

 [colors.bright]
 black="0x767676"
 red="0xe74856"
 green="0x16c60c"
 yellow="0xf9f1a5"
 blue="0x3b78ff"
 magenta="0xb4009e"
 cyan="0x61d6d6"
 white="0xf2f2f2"

 [colors.primary]
 background = "#000000"
 foreground = "#f8f8f2"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
normal = { family = "Meslo LG M DZ", style = "Regular" }
# family = "MesloLGS NF"
size = 8

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^╬ô╞Æ┬┐╬ô╞ÆΓîÉ╬ô├ç├┐]+"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[[keyboard.bindings]]
key="Space"
mods="Control"
chars = "\u0000"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",╬ô├╢├⌐`|:\"' ()[]{}<>"

[shell]
program = "wsl --cd ~"

[window]
decorations = "full"
startup_mode = "Maximized"
opacity = 0.70
title = "Alacritty"
dynamic_title = true

[window.dimensions]
columns = 175
lines = 100

[window.padding]
x = 0
y = 0

[window.position]
x = 70
y = 70
