- packages:
    - pacman: python3
    - chocolatey: python

- packages:
    pip:
      - requests
      - package: RequestMixin
        git: mohkale
      - package: DownloadQueue
        git: mohkale
