- packages:
    - apt:
        - python3
        - python3-pip
    - msys: python
    - chocolatey: python
    - pacman: python3

- packages:
    pip:
      - requests
      - youtube-dl
      - package: RequestMixin
        git: mohkale
      - package: DownloadQueue
        git: mohkale
