- link:
    ~/.config/pythonrc.py: pythonrc
    ~/.pdbrc:
    ~/.config/pdbrc.py:

- packages:
    - apt:
        - python3
        - python3-pip
    - msys: python
    - chocolatey: python
    - pacman:
      - python3
      - python-pip

- packages:
    pip:
      - requests
      - youtube-dl
      - beautifulsoup4
      - package: RequestMixin
        git: mohkale
      - package: DownloadQueue
        git: mohkale
