- defaults:
    link:
      force: true
      create: true

- link:
    ~/.profile:
    ~/.config/shenv:
    ~/.config/xdg:
    ~/.config/bindings/readline: inputrc
    ~/programming/scripts/.ps1: prompt
