- link:
    ~/.config/kglobalshortcutsrc: shortcuts
    ~/.config/kdeglobals: settings

- bots:
    - path: ../xorg
      unsafe: true

- packages:
    pacman:
      - plasma-meta

- bots:
    - path: ../../programs/dolphin
      unsafe: true
    - path: ../../programs/spectacle
      unsafe: true
