# dotbot configuration file
- defaults:
    link:
      relink: true
      create: true
    bots:
      config: config.yml

- clean: ['~']

- create:
    - ~/downloads
    - ~/multifolder
    - ~/multimedia
    - ~/multimedia/images
    - ~/multimedia/videos
    - ~/multimedia/music
    - ~/programming
    - ~/programming/misc
    - ~/programming/repos
    - ./setup/cache

- shell:
    # determine the platform dotfiles are being
    # installed into. works by dumping a file with
    # the same name as the platform to ./setup/dist.
    - description: Discovering Current Platform
      quiet: true
      command: |-
        dest_dir=./setup/cache/dist/
        rm -rf "$dest_dir"
        mkdir -p "$dest_dir"

        platform=$(./setup/platform)
        if [ ! -z "$platform" ]; then
          touch "$dest_dir/$platform"
        fi

- bots:
    - core

    # platform specific setups.
    - path: dist/arch
      when: |-
        [ ! -z "$install" ] &&
        [ -f ./setup/cache/dist/arch ]

    - path: dist/msys
      when: |-
        [ ! -z "$install" ] &&
        [ -f ./setup/cache/dist/windows ]

    - path: dist/ubuntu
      when: |-
        [ ! -z "$install" ] &&
        [ -f ./setup/cache/dist/ubuntu ]

    # subbot directories
    - desktop
    - editors
    - langs
    - programs
    - scripts
    - shells
