- link:
    ~/.gemrc:
    ~/.config/irb/irbrc:
    ~/.pryrc:
    ~/.rvmrc:

- packages:
    # if you have issues with gem install on cygwin, try
    # [[https://github.com/rubygems/rubygems/issues/2483][this]] to see if it fixes the issue.
    - cygwin: ruby
    - chocolatey: ruby

- packages:
    - gem:
        - colorize
