- packages:
    - yay: dropbox
    - chocolatey: dropbox

- link:
    ../../editors/emacs/org:
      path: ~/Dropbox/org
      create:         true
      ignore-missing: true
      if: |-
        grep -iE emacs <<< "$DOTBOTS"
