- link:
    ~/.config/aliases:
    ~/.config/shortcuts:

- bots:
    - config
    - sh
    - path: fonts
      tasks:
        - clean:
            - ~/.local/share/fonts/
        - link:
            ~/.local/share/fonts/:
              path: "*.ttf"
              glob: true
        - link:
            ~/.local/share/fonts/:
              path: "*.otf"
              glob: true
