- packages:
    - apt: tmux
    - msys: tmux
    - pacman: tmux

- link:
    ~/.tmux/tmuxrc: tmuxrc

- bots:
    - scripts

- create:
    - ~/.tmux/tmp

- populate:
    - path: ~/.tmux.conf
      body: source-file ~/.tmux/tmuxrc
      skip: True
