- packages:
    - apt: vim
    - msys: vim
    - chocolatey: vim
    # also provides clipboard support
    - pacman: gvim

- create:
    - ~/.vim

- link:
    ~/.vimrc:
    ~/_vimrc:
      path: ~/.vimrc
      if: &windows-p "[ -e '../../setup/cache/dist/windows' ]"
    ~/_vim:
      path: ~/.vim
      if: *windows-p

- shell:
    - description: Install Vim Plug
      interactive: true
      quiet: true
      command: |-
        autoload_path=~/.vim/autoload/plug.vim
        autoload_url='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        if ! [ -f "$autoload_path" ]; then
          curl -fLo "$autoload_path" --create-dirs "$autoload_url"
        fi

        vim -c :PlugInstall -c ':qa!'
