- link:
    ~/.config/transmission/settings.json:
    ~/.config/transmission-cli: settings.json
    ~/.config/transmission-daemon/settings.json: settings.json
    ~/.config/tremc/settings.cfg: tremcrc
    ~/.config/transmission-daemon/watcher.json: watch.json

- bots: scripts

- packages:
    - yay:
        - transmission-cli-git # daemon
        - transmission-qt      # gui
        - tremc-git            # curses
    - apt:
        - package: transmission-cli
          before: |-
            sudo add-apt-repository ppa:transmissionbt/ppa
            sudo apt update
        - transmission-common
        - transmission-daemon
