---
version: "1"
services:
  jellyfin:
    image: jellyfin/jellyfin
    build:
      dockerfile: jellyfin.docker
      args:
        DOTNET_VERSION: '6.0'
    container_name: jellyfin
    network_mode: host
    volumes:
      - $XDG_CACHE_HOME/jellyfin:/cache
      - $XDG_CONFIG_HOME/jellyfin:/config
      # Download folders often contain new media before I back them up.
      - ${JELLYFIN_SKIP_DOWNLOAD:-$XDG_DOWNLOAD_DIR}:/media/downloads:ro
      # Dedicated home level directories for media files. I often symlink
      # these into a larger main drive, but docker-compose will fail to
      # startup if that drive isn't mounted so here we silently ignore
      # them.
      - ${JELLYFIN_SKIP_MUSIC:-$XDG_MUSIC_DIR}:/media/music:ro
      - ${JELLYFIN_SKIP_MOVIES:-$XDG_VIDEOS_DIR/movies}:/media/movies:ro
      - ${JELLYFIN_SKIP_TV:-$XDG_VIDEOS_DIR/tv}:/media/tv:ro
      - ${JELLYFIN_SKIP_AMV:-$XDG_VIDEOS_DIR/AMV}:/media/amv:ro
      - ${JELLYFIN_SKIP_MANGA:-$HOME/media/manga}:/media/manga:ro
      # This directory is the dedicated mount root for media related drives.
      - /mnt/media:/media/mount:ro
    restart: unless-stopped
