- clean:
    ~/programming/scripts:
      recursive: true

- link:
    ~/programming/scripts/vipe:
    ~/programming/scripts/spawn-term:
    ~/programming/scripts/image2ascii:
    ~/programming/scripts/fp: file-path
    ~/programming/scripts/private:
      path: private/*
      glob: true

- bots:
    - path: emacs
      env:  true
