
[[Snippets]]
  Description = "List All AUR packages"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "paru -Qmq"

[[Snippets]]
  Description = "Startup SSH Agent and prompt for key to add"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "eval $(ssh-agent -c) && ssh-add $(rg --files ~/.ssh | fzf)"

[[Snippets]]
  Description = "Clear pacman cache"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "paccache -ruvk 0"

[[Snippets]]
  Description = "Fuzzy search dirs from $HOME and cd"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "cd $(fd -td --search-path ~/ | fzf | xargs echo)"

[[Snippets]]
  Description = "Fuzzy Search a process and kill it"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "kill -9 --verbose $(ps aux | fzf | awk '{ print $2 }')"

[[Snippets]]
  Description = "List Explicitly installed pacman packages"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "pacman -Qent"

[[Snippets]]
  Description = "Browse pacman packages (installed and not)"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "$ pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse"

[[Snippets]]
  Description = "OS Info"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "uname -a"

[[Snippets]]
  Description = "CPU Info"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "lscpu --output-all"

[[Snippets]]
  Description = "List Orphaned Pacman packages"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "pacman -Qtdq"

[[Snippets]]
  Description = "List and Delete all broken symlinks"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "rm -v (sudo czkawka-cli symlinks -d /bin/ -d /boot/ -d /etc/ -d /home/ -d /lib/ -d /lib64/ -d /opt/ -d /root/ -d /run/ -d /sbin/ -d /srv/ -d /sys/ -d /tmp/ -d /usr/ -d /var | awk '{ print $1 }' | sed 's/\"//g')"

[[Snippets]]
  Description = "Clean journal logs older than 1 week"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "sudo journalctl --vacuum-time=1weeks"

[[Snippets]]
  Description = "Fuzzy Select install PacMan packages and remove them"
  Filename = "/home/atan/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "sudo pacman -Rns $(pacman -Qq | fzf --preview \"pacman -Qqi {}\" --multi --bind tab:select --bind shift-tab:deselect)"
