---
services:
  caddy:
    container_name: ms-caddy
    environment:
      SITE_ADDRESS: "$SITE_ADDRESS"
    image: caddy:latest
    logging:
      driver: "$LOGGING_DRIVER"
    ports:
      - "80:80"
      # SSL ports needed to be able to route through HTTPs.
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/proxy:/etc/caddy
      # We put data into $XDG_CONFIG_HOME because it should be persisted.
      # It may contain letsencrypt certificates or other configurations
      # that you don't want to be removed.
      - $XDG_CONFIG_HOME/media-server/caddy/data:/data
      - $XDG_CONFIG_HOME/media-server/caddy/config:/config

  error-pages:
    container_name: ms-error-pages
    environment:
      TEMPLATE_NAME: app-down
      SEND_SAME_HTTP_CODE: true
      SHOW_DETAILS: true
    image: ghcr.io/tarampampam/error-pages
    logging:
      driver: "$LOGGING_DRIVER"
    restart: unless-stopped
