---
services:
  kavita:
    container_name: ms-kavita
    depends_on:
      - caddy
    image: jvmilazz0/kavita:latest
    logging:
      driver: "$LOGGING_DRIVER"
    profiles:
      - comics
    restart: unless-stopped
    volumes:
      - $XDG_MEDIA_HOME/content:/media/content:ro
      - $XDG_CONFIG_HOME/media-server/kavita:/kavita/config
