---
version: "2.2"
services:
  shoko:
    container_name: ms-shoko
    depends_on:
      - caddy
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      TZ: "$TZ"
    image: shokoanime/server:latest
    logging:
      driver: "$LOGGING_DRIVER"
    profiles:
      - anime
    restart: unless-stopped
    volumes:
      - $XDG_CONFIG_HOME/media-server/shoko:/home/shoko/.shoko/
      - $XDG_MEDIA_HOME:/media
