---
services:
  bazarr:
    container_name: ms-bazarr
    depends_on:
      - caddy
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      TZ: "$TZ"
    image: lscr.io/linuxserver/bazarr:latest
    logging:
      driver: "$LOGGING_DRIVER"
    profiles:
      - anime
      - movies
      - tv-shows
    restart: unless-stopped
    volumes:
      - $XDG_MEDIA_HOME/content:/media/content
      - $XDG_CONFIG_HOME/media-server/bazarr:/config
