---
version: "2.2"
services:
  readarr:
    container_name: ms-readarr
    depends_on:
      - caddy
      - prowlarr
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Europe/London
    image: lscr.io/linuxserver/readarr:develop
    logging:
      driver: $LOGGING_DRIVER
    profiles:
      - books
      - comics
    restart: unless-stopped
    volumes:
      - $XDG_CONFIG_HOME/media-server/readarr:/config
      - $XDG_MEDIA_HOME:/media
