---
version: "2.2"
services:
  radarr:
    container_name: ms-radarr
    depends_on:
      - caddy
      - prowlarr
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      TZ: "$TZ"
    image: lscr.io/linuxserver/radarr:latest
    logging:
      driver: "$LOGGING_DRIVER"
    profiles:
      - movies
    restart: unless-stopped
    volumes:
      - $XDG_CONFIG_HOME/media-server/radarr:/config
      - $XDG_MEDIA_HOME:/media
