---
services:
  lidarr:
    container_name: ms-lidarr
    depends_on:
      - caddy
      - prowlarr
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      TZ: "$TZ"
    image: lscr.io/linuxserver/lidarr:latest
    logging:
      driver: $LOGGING_DRIVER
    profiles:
      - music
    restart: unless-stopped
    volumes:
      - $XDG_CONFIG_HOME/media-server/lidarr:/config
      - $XDG_MEDIA_HOME:/media
