---
services:
  prowlarr:
    container_name: ms-prowlarr
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      TZ: "$TZ"
    image: lscr.io/linuxserver/prowlarr:develop
    logging:
      driver: "$LOGGING_DRIVER"
    profiles:
      - anime
      - books
      - comics
      - movies
      - music
      - tv-shows
    restart: unless-stopped
    volumes:
      - $XDG_CONFIG_HOME/media-server/prowlarr:/config
