---
services:
  heimdall:
    container_name: ms-heimdall
    depends_on:
      - caddy
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      TZ: "$TZ"
    image: lscr.io/linuxserver/heimdall:latest
    logging:
      driver: "$LOGGING_DRIVER"
    profiles:
      - dashboard
    restart: unless-stopped
    volumes:
      - $XDG_CONFIG_HOME/media-server/heimdall:/config
