---
services:
  authelia:
    container_name: ms-authelia
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      TZ: "$TZ"
    image: authelia/authelia:latest
    logging:
      driver: "$LOGGING_DRIVER"
    restart: unless-stopped
    volumes:
      - $XDG_CONFIG_HOME/media-server/authelia:/config

  caddy:
    depends_on:
      authelia:
        condition: service_healthy

  navidrome:
    environment:
      ND_REVERSEPROXYUSERHEADER: "Remote-User"
      # If logged in correctly when reverse proxying through Caddy
      # then bypass the navidrome login wall. We allow passthrough
      # for all IP subnets. This should be fine because the service
      # is only exposed through Caddy. Nothing will be proxying to
      # it with the REVERSEPROXYUSERHEADER on localhost and on remote
      # connections it should be authorized with authelia.
      ND_REVERSEPROXYWHITELIST: 0.0.0.0/0
