-- Presets
---@class WaybarPreset
---@field flag number
---@field height number|nil
---@field position string
---@field modules_left string[]|string[][]
---@field modules_center string[]|string[][]
---@field modules_right string[]|string[][]

---@type WaybarPreset[]
return {
	{
		flag = 0,
		height = 28,
		position = "bottom",
		modules_left = { { "cpu", "memory", "custom/cpuinfo", "custom/gpuinfo" }, { "idle_inhibitor", "clock" } },
		modules_center = { { "hyprland/workspaces", "hyprland/window" } },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates", "custom/keybindhint" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 1,
		height = 28,
		position = "top",
		modules_left = {
			{ "cpu", "memory", "custom/cpuinfo", "custom/gpuinfo" },
			{ "idle_inhibitor", "clock", "custom/niflveil" },
		},
		modules_center = { { "hyprland/workspaces", "hyprland/window" } },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates", "custom/keybindhint" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 28,
		position = "bottom",
		modules_left = {
			{ "cpu", "memory", "custom/cpuinfo", "custom/gpuinfo" },
			{ "idle_inhibitor", "clock" },
			{ "hyprland/workspaces" },
		},
		modules_center = { "hyprland/window" },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates", "custom/keybindhint" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 28,
		position = "top",
		modules_left = {
			{ "cpu", "memory", "custom/cpuinfo" },
			{ "idle_inhibitor", "clock" },
			{ "hyprland/workspaces" },
		},
		modules_center = { "hyprland/window" },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates", "custom/keybindhint" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = nil,
		position = "bottom",
		modules_left = { { "hyprland/workspaces", "hyprland/window" } },
		modules_center = { "idle_inhibitor", "clock" },
		modules_right = {
			{ "cpu", "memory", "custom/cpuinfo", "custom/gpuinfo" },
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates", "custom/keybindhint" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = nil,
		position = "top",
		modules_left = { { "hyprland/workspaces", "hyprland/window" } },
		modules_center = { "idle_inhibitor", "clock" },
		modules_right = {
			{ "cpu", "memory", "custom/cpuinfo", "custom/gpuinfo" },
			{
				"backlight",
				"network",
				"pulseaudio",
				"pulseaudio#microphone",
				"custom/updates",
				"custom/keybindhint",
				"custom/weather",
			},
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 31,
		position = "bottom",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "wlr/taskbar", "custom/spotify" },
		},
		modules_center = { "idle_inhibitor", "clock" },
		modules_right = {
			{ "privacy", "tray", "battery" },
			{
				"backlight",
				"network",
				"pulseaudio",
				"pulseaudio#microphone",
				"custom/notifications",
				"custom/keybindhint",
			},
		},
	},
	-- 0|31|left|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( privacy tray battery ) ( backlight network pulseaudio pulseaudio#microphone custom/keybindhint )
	{
		flag = 0,
		height = 31,
		position = "left",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "wlr/taskbar", "custom/spotify" },
		},
		modules_center = { { "idle_inhibitor", "clock" } },
		modules_right = {
			{ "privacy", "tray", "battery" },
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/keybindhint" },
		},
	},
	{
		flag = 0,
		height = 31,
		position = "top",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "wlr/taskbar", "custom/spotify" },
		},
		modules_center = { { "idle_inhibitor", "clock" } },
		modules_right = {
			{ "privacy", "tray", "battery" },
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/keybindhint" },
		},
	},
	{
		flag = 0,
		height = 31,
		position = "right",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "wlr/taskbar", "custom/spotify" },
		},
		modules_center = { { "idle_inhibitor", "clock" } },
		modules_right = {
			{ "privacy", "tray", "battery" },
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/keybindhint" },
		},
	},
	{
		flag = 0,
		height = 32,
		position = "bottom",
		modules_left = {},
		modules_center = {
			{ "custom/power" },
			{ "privacy", "tray", "battery" },
			{ "wlr/taskbar", "idle_inhibitor", "clock" },
			{ "custom/cliphist" },
			{ "custom/wbar" },
			{ "custom/wallchange" },
			{ "custom/theme" },
		},
		modules_right = {},
	},
	{
		flag = 0,
		height = 32,
		position = "left",
		modules_left = {},
		modules_center = {
			{ "custom/power" },
			{ "privacy", "tray", "battery" },
			{ "wlr/taskbar", "idle_inhibitor", "clock" },
			{ "custom/cliphist" },
			{ "custom/wbar" },
			{ "custom/wallchange" },
			{ "custom/theme" },
		},
		modules_right = {},
	},
	{
		flag = 0,
		height = 32,
		position = "top",
		modules_left = {},
		modules_center = {
			{ "custom/power" },
			{ "privacy", "tray", "battery" },
			{ "wlr/taskbar", "idle_inhibitor", "clock" },
			{ "custom/cliphist" },
			{ "custom/wbar" },
			{ "custom/wallchange" },
			{ "custom/theme" },
		},
		modules_right = {},
	},
	{
		flag = 0,
		height = 32,
		position = "right",
		modules_left = {},
		modules_center = {
			{ "custom/power" },
			{ "privacy", "tray", "battery" },
			{ "wlr/taskbar", "idle_inhibitor", "clock" },
			{ "custom/cliphist" },
			{ "custom/wbar" },
			{ "custom/wallchange" },
			{ "custom/theme" },
		},
		modules_right = {},
	},
	{
		flag = 0,
		height = 31,
		position = "bottom",
		modules_left = {
			{ "cpu", "memory", "custom/cpuinfo", "custom/gpuinfo" },
			{ "idle_inhibitor", "clock" },
			{ "hyprland/workspaces" },
		},
		modules_center = { "wlr/taskbar" },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates", "custom/keybindhint" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 31,
		position = "top",
		modules_left = {
			{ "cpu", "memory", "custom/cpuinfo", "custom/gpuinfo" },
			{ "idle_inhibitor", "clock" },
			{ "hyprland/workspaces" },
		},
		modules_center = { "wlr/taskbar" },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates", "custom/keybindhint" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 29,
		position = "bottom",
		modules_left = { { "wlr/taskbar", "mpris" } },
		modules_center = { { "idle_inhibitor", "clock" } },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 29,
		position = "left",
		modules_left = { { "wlr/taskbar", "mpris" } },
		modules_center = { { "idle_inhibitor", "clock" } },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 29,
		position = "top",
		modules_left = { { "wlr/taskbar", "mpris" } },
		modules_center = { { "idle_inhibitor", "clock" } },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 29,
		position = "right",
		modules_left = { { "wlr/taskbar", "mpris" } },
		modules_center = { { "idle_inhibitor", "clock" } },
		modules_right = {
			{ "backlight", "network", "pulseaudio", "pulseaudio#microphone", "custom/updates" },
			{ "privacy", "tray", "battery" },
			{ "custom/wallchange", "custom/theme", "custom/wbar", "custom/cliphist", "custom/power" },
		},
	},
	{
		flag = 0,
		height = 28,
		position = "bottom",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "idle_inhibitor", "clock", "custom/spotify" },
		},
		modules_center = { "wlr/taskbar" },
		modules_right = { { "privacy", "tray" }, { "backlight", "network", "pulseaudio", "pulseaudio#microphone" } },
	},
	{
		flag = 0,
		height = 28,
		position = "left",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "idle_inhibitor", "clock", "custom/spotify" },
		},
		modules_center = { "wlr/taskbar" },
		modules_right = { { "privacy", "tray" }, { "backlight", "network", "pulseaudio", "pulseaudio#microphone" } },
	},
	{
		flag = 0,
		height = 28,
		position = "top",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "idle_inhibitor", "clock", "custom/spotify" },
		},
		modules_center = { "wlr/taskbar" },
		modules_right = { { "privacy", "tray" }, { "backlight", "network", "pulseaudio", "pulseaudio#microphone" } },
	},
	{
		flag = 0,
		height = 28,
		position = "right",
		modules_left = {
			{ "custom/power", "custom/cliphist", "custom/wbar", "custom/theme", "custom/wallchange" },
			{ "idle_inhibitor", "clock", "custom/spotify" },
		},
		modules_center = { "wlr/taskbar" },
		modules_right = { { "privacy", "tray" }, { "backlight", "network", "pulseaudio", "pulseaudio#microphone" } },
	},
	{
		flag = 0,
		height = 40,
		position = "top",
		modules_left = { { "hyprland/workspaces" } },
		modules_center = { { "custom/cava", "idle_inhibitor", "clock" } },
		modules_right = {
			{
				"backlight",
				"pulseaudio",
				"pulseaudio#microphone",
				"tray",
				"battery",
				"custom/keybindhint",
				"custom/cliphist",
				"custom/hyprsunset",
				"custom/power",
			},
		},
	},
	{
		flag = 0,
		height = 30,
		position = "top",
		modules_left = { { "hyprland/workspaces##kanji", "wlr/taskbar##custom" } },
		modules_center = {
			{
				"keyboard-state",
				"custom/hyprsunset",
				"idle_inhibitor",
				"clock##alt",
				"custom/updates",
				"custom/keybindhint",
			},
		},
		modules_right = {
			{
				"privacy",
				"backlight",
				"tray",
				"network",
				"custom/bluetooth",
				"pulseaudio",
				"pulseaudio#microphone",
				"battery",
				"custom/gpuinfo",
				"custom/swaync",
			},
		},
	},
	{
		flag = 0,
		height = 30,
		position = "bottom",
		modules_left = {},
		modules_center = { { "wlr/taskbar##windows" } },
		modules_right = {
			{
				"privacy",
				"tray",
				"custom/gpuinfo",
				"network",
				"pulseaudio",
				"pulseaudio#microphone",
				"battery",
				"clock",
			},
		},
	},
}
